project_id = "txhakmrteltbbabpvlmu"

[functions.chat]
verify_jwt = false

[functions.elevenlabs-conversation-token]
verify_jwt = false

[functions.elevenlabs-scribe-token]
verify_jwt = false

[functions.elevenlabs-stt]
verify_jwt = false

[functions.elevenlabs-tts]
verify_jwt = false

[functions.webhook-research]
verify_jwt = false

[functions.webhook-send-text]
verify_jwt = false

[functions.webhook-create-automation]
verify_jwt = false
