project_id = "txhakmrteltbbabpvlmu"

[functions.chat]
verify_jwt = false

[functions.rag-chat]
verify_jwt = false

[functions.webhook-research]
verify_jwt = false

[functions.webhook-send-text]
verify_jwt = false

[functions.webhook-create-automation]
verify_jwt = false

[functions.vapi-webhook]
verify_jwt = false

[functions.analyze-conversation]
verify_jwt = false

[functions.enhance-prompt]
verify_jwt = false

[functions.generate-fix-prompt]
verify_jwt = false

[functions.generate-embedding]
verify_jwt = false

[functions.linkedin-research]
verify_jwt = false

[functions.vapi-chat]
verify_jwt = false
